# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0438')),
                ('tare_number', models.PositiveIntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0430\u0440\u044b')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u041e\u0431\u044a\u0435\u043c')),
                ('number_pumping', models.PositiveIntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043e\u0442\u043a\u0430\u0447\u043a\u0438')),
                ('honey_type', models.CharField(max_length=32, verbose_name='\u041c\u0451\u0434')),
                ('kind', models.PositiveSmallIntegerField(choices=[(2, '\u0414\u043b\u044f \u0441\u0435\u0431\u044f'), (1, '\u041a\u0443\u043f\u0438\u043b'), (0, '\u041f\u043e\u0434\u0430\u0440\u043e\u043a')], verbose_name='\u0422\u0438\u043f \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0412\u0435\u0441')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u0426\u0435\u043d\u0430')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u041e\u043f\u043b\u0430\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0434\u0430\u0436\u0430',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0430\u0436\u0438',
            },
        ),
    ]
